name: Build Custom RustDesk Client

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    env:
      RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
      RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@stable

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Install vcpkg deps
        run: |
          git clone https://github.com/microsoft/vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static aom:x64-windows-static
          echo "VCPKG_ROOT=$PWD\vcpkg" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build
        run: |
          python build.py --portable --flutter

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-lunexa-client
          path: |
            **/*.exe
